version: '3.8'

services:
  multilingual-rag-planner:
    build: .
    ports:
      - "8501:8501"
    environment:
      # Supabase Configuration
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      
      # OpenAI Configuration
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-3.5-turbo}
      
      # Application Settings
      - APP_NAME=${APP_NAME:-Multilingual RAG Planner}
      - DEBUG_MODE=${DEBUG_MODE:-False}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      
      # Vector Database Settings
      - CHROMA_PERSIST_DIRECTORY=/app/chroma_db
      - EMBEDDINGS_MODEL=${EMBEDDINGS_MODEL:-all-MiniLM-L6-v2}
      
      # Task Generation Settings
      - MAX_DAILY_TASKS=${MAX_DAILY_TASKS:-10}
      - PLANNING_HORIZON_DAYS=${PLANNING_HORIZON_DAYS:-30}
      
      # Multilingual Settings
      - DEFAULT_LANGUAGE=${DEFAULT_LANGUAGE:-en}
    
    volumes:
      - chroma_data:/app/chroma_db
      - app_logs:/app/logs
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  chroma_data:
    driver: local
  app_logs:
    driver: local

networks:
  default:
    driver: bridge